# Numerical Python(Numpy) - Part1

In [1]:
# de facto standard (사실상의 표준)
import numpy as np

In [2]:
a = [1,2,3]
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [3]:
list(map(lambda x:3*x,a))

[3, 6, 9]

In [4]:
b = np.array([1,2,3])
b*3

array([3, 6, 9])

## 1. Numpy Dimensional Array

In [5]:
a = np.array([1,4,5,8],float)
a

array([1., 4., 5., 8.])

In [7]:
type(a)

numpy.ndarray

In [8]:
a.dtype, a.shape            # a.shape : 차원, 튜플형으로 출력, 매우 많이 사용

(dtype('float64'), (4,))

## 2. Array shape

In [12]:
#Vector(1차원)
vector = np.array([1,4,5,8])
vector.shape

(4,)

In [17]:
# Matrix(2차원)
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix.shape)
print(matrix)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [23]:
# Tensor(3차원 이상)
tensor = np.arange(1,25).reshape(2,3,4)
print(tensor)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [24]:
tensor.shape        # (평면, 행, 열)

(2, 3, 4)

In [25]:
vector.shape, matrix.shape, tensor.shape

((4,), (2, 3), (2, 3, 4))

In [26]:
# element의 갯수
vector.size, matrix.size, tensor.size

(4, 6, 24)

In [27]:
# data type
# float32 : 32bit로 표시 - single precision
# float64 : 64bit로 표시 - double precision
a = np.array([1,2,3],dtype = np.float32)
a

array([1., 2., 3.], dtype=float32)

In [28]:
b = np.array([1,2,3],dtype = np.int16) # int16 : short, int64 : long
b

array([1, 2, 3], dtype=int16)

### reshape

In [29]:
# reshape
matrix.shape

(2, 3)

In [30]:
matrix.reshape(6,)  # 2차원 -> 1차원, ','주의!

array([1, 2, 3, 4, 5, 6])

In [32]:
matrix.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
# -1은 numpy가 알아서 맞춰줌, -1은 하나만 가능!, 자주 사용됨 (단, size가 동일)
matrix.reshape(-1,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
matrix.reshape(3,-1).shape

(3, 2)

In [35]:
matrix.reshape(-1,)

array([1, 2, 3, 4, 5, 6])

In [38]:
tensor.reshape(4,-1).shape

(4, 6)

In [39]:
matrix.reshape(-1,)         # 열 6개 (1차원), 행벡터

array([1, 2, 3, 4, 5, 6])

In [40]:
matrix.reshape(1,-1)        # 행 1개, 열 6개    (2차원)

array([[1, 2, 3, 4, 5, 6]])

In [41]:
matrix.reshape(-1,1)        # 행 6개, 열 1개

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

### flatten

In [48]:
tensor.reshape(-1,)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [49]:
tensor.flatten()        # 차원 상관없이 1차원으로 변환

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

## 3. Indexing & Slicing

### Indexing

In [45]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
matrix[0][1]

2

In [47]:
matrix[0,1]

2

In [50]:
tensor[1,1,2]

19

### Slicing

In [52]:
b = np.arange(16).reshape(4,-1)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [53]:
# 5,6,9,10
b[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [54]:
# 5,6,7,9,10,11
b[1:3,1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [57]:
# 1,3,9,10
b[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [60]:
# 2차원 이상 : 대문자, 1차원 : 소문자
X, y = b[:,:-1], b[:,-1]
X.shape, y.shape

((4, 3), (4,))

In [ ]:
# 슬라이싱은 차원 유지, 인덱싱은 한 차원씩 감소