# DataFrame class

In [1]:
import numpy as np
import pandas as pd

## 생성

In [6]:
# 열방향 인덱스는 columns 인수로, 행방향 인덱스는 index 인수
data = {
    "2015": [9904312, 3448737, 2890451, 2466052],
    "2010": [9631482, 3393191, 2632035, 2431774],
    "2005": [9762546, 3512547, 2517680, 2456016],
    "2000": [9853972, 3655437, 2466338, 2473990],
    "지역": ["수도권", "경상권", "수도권", "경상권"],       # 하나의 열은 동일한 데이터타입을 갖고 있어야 함
    "2010-2015 증가율": [0.0283, 0.0163, 0.0982, 0.0141]    # 각각의 행은 다른 데이터타입을 갖고 있을 수 있음
}
columns = ["지역", "2015", "2010", "2005", "2000", "2010-2015 증가율"]  # 열 인덱스
index = ["서울", "부산", "인천", "대구"]    # 행 인덱스
df = pd.DataFrame(data, index=index, columns=columns) # DataFrame 클래스는 2차원 행렬 데이터에 행/열인덱스를 붙인 것
df

지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [ ]:
# data를 입력할 대 딕셔너리로 키값을 주기 때문에 열 인덱스는 생략하여도 결과가 동일함
data = {
    "지역": ["수도권", "경상권", "수도권", "경상권"],
    "2015": [9904312, 3448737, 2890451, 2466052],
    "2010": [9631482, 3393191, 2632035, 2431774],
    "2005": [9762546, 3512547, 2517680, 2456016],
    "2000": [9853972, 3655437, 2466338, 2473990],
    "2010-2015 증가율": [0.0283, 0.0163, 0.0982, 0.0141]
}

index = ["서울", "부산", "인천", "대구"]
df = pd.DataFrame(data, index=index, columns=columns)
df

지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [7]:
df.지역.values

array(['수도권', '경상권', '수도권', '경상권'], dtype=object)

In [8]:
df['2015'].values

array([9904312, 3448737, 2890451, 2466052])

In [9]:
df.columns

Index(['지역', '2015', '2010', '2005', '2000', '2010-2015 증가율'], dtype='object')

In [10]:
df.index.name = '도시'
df.columns.name = '특성'
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [33]:
data = np.arange(24).reshape(4,6)
columns = ["지역", "2015", "2010", "2005", "2000", "2010-2015 증가율"]
index = ["서울", "부산", "인천", "대구"]
df2 = pd.DataFrame(data, index=index, columns=columns)   # data에는 2차원 행렬 데이터가 입력되어야 함
df2

지역  2015  2010  2005  2000  2010-2015 증가율
서울   0     1     2     3     4              5
부산   6     7     8     9    10             11
인천  12    13    14    15    16             17
대구  18    19    20    21    22             23

In [11]:
df.T    # 전치

도시                  서울       부산       인천       대구
특성                                               
지역                 수도권      경상권      수도권      경상권
2015           9904312  3448737  2890451  2466052
2010           9631482  3393191  2632035  2431774
2005           9762546  3512547  2517680  2456016
2000           9853972  3655437  2466338  2473990
2010-2015 증가율   0.0283   0.0163   0.0982   0.0141

## 열 데이터의 갱신, 추가, 삭제

In [12]:
df['2010-2015 증가율'] = df['2010-2015 증가율']*100 # 백분율로 표현, update
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972           2.83
부산  경상권  3448737  3393191  3512547  3655437           1.63
인천  수도권  2890451  2632035  2517680  2466338           9.82
대구  경상권  2466052  2431774  2456016  2473990           1.41

In [14]:
df['2020'] = [1,2,3,4]  # 추가, create
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율  2020
도시                                                              
서울  수도권  9904312  9631482  9762546  9853972           2.83     1
부산  경상권  3448737  3393191  3512547  3655437           1.63     2
인천  수도권  2890451  2632035  2517680  2466338           9.82     3
대구  경상권  2466052  2431774  2456016  2473990           1.41     4

In [16]:
del df['2020']  # delete
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972           2.83
부산  경상권  3448737  3393191  3512547  3655437           1.63
인천  수도권  2890451  2632035  2517680  2466338           9.82
대구  경상권  2466052  2431774  2456016  2473990           1.41

## 열 인덱싱

In [17]:
df['지역']  # 결과는 Series

도시
서울    수도권
부산    경상권
인천    수도권
대구    경상권
Name: 지역, dtype: object

In [18]:
df[['지역','2015']] # 원소가 1개 이상인 리스트로 인덱싱하면 결과는 DataFrame

특성   지역     2015
도시              
서울  수도권  9904312
부산  경상권  3448737
인천  수도권  2890451
대구  경상권  2466052

In [19]:
df[['지역']]    # 결과는 DataFrame

특성   지역
도시     
서울  수도권
부산  경상권
인천  수도권
대구  경상권

In [20]:
type(df['지역']), type(df[['지역']])

(pandas.core.series.Series, pandas.core.frame.DataFrame)

## 행 인덱싱

In [22]:
# 행 단위로 인덱싱을 하고자 하면 항상 슬라이싱(slicing)을 해야 한다.
df[:'서울'] # df['서울']은 오류, 슬라이싱을 해야 함.

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972           2.83

In [23]:
df[1:2]

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
부산  경상권  3448737  3393191  3512547  3655437           1.63

In [24]:
df['부산':'인천']

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
부산  경상권  3448737  3393191  3512547  3655437           1.63
인천  수도권  2890451  2632035  2517680  2466338           9.82

In [25]:
df.head(3)  # 행 인덱싱보다는 head와 tail을 사용, head() 앞에서부터 행 출력

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972           2.83
부산  경상권  3448737  3393191  3512547  3655437           1.63
인천  수도권  2890451  2632035  2517680  2466338           9.82

In [26]:
df.tail(3)  # 뒤에서부터 행 출력

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
부산  경상권  3448737  3393191  3512547  3655437           1.63
인천  수도권  2890451  2632035  2517680  2466338           9.82
대구  경상권  2466052  2431774  2456016  2473990           1.41

## 개별 데이터 인덱싱
- df['열 이름']['행 이름']

In [28]:
df['2015']['서울'], df['2015'][0]

(9904312, 9904312)

### 연습 문제 4.1.3

In [31]:
data = {
    "국어": [80, 90, 70, 30],
    "영어": [90, 70, 60, 40],
    "수학": [90, 60, 80, 70],
}
columns = ["국어", "영어", "수학"]
index = ["춘향", "몽룡", "향단", "방자"]
df = pd.DataFrame(data, index=index, columns=columns)
df

국어  영어  수학
춘향  80  90  90
몽룡  90  70  60
향단  70  60  80
방자  30  40  70

In [32]:
# (1) 모든 학생의 수학 점수를 시리즈로 나타낸다.
df['수학']

춘향    90
몽룡    60
향단    80
방자    70
Name: 수학, dtype: int64

In [34]:
# (2) 모든 학생의 국어와 영어 점수를 데이터 프레임으로 나타낸다.
df[['국어','영어']]

국어  영어
춘향  80  90
몽룡  90  70
향단  70  60
방자  30  40

In [37]:
# (3) 모든 학생의 각 과목 평균 점수를 새로운 열로 추가한다.
df.values

array([[80, 90, 90],
       [90, 70, 60],
       [70, 60, 80],
       [30, 40, 70]])

In [40]:
np.mean(df.values,axis=1).round(1)

array([86.7, 73.3, 70. , 46.7])

In [41]:
df['평균'] = np.mean(df.values,axis=1).round(1)
df

국어  영어  수학    평균
춘향  80  90  90  86.7
몽룡  90  70  60  73.3
향단  70  60  80  70.0
방자  30  40  70  46.7

In [42]:
df.mean(axis=1)

춘향    86.675
몽룡    73.325
향단    70.000
방자    46.675
dtype: float64

In [45]:
# (4) 방자의 영어 점수를 80점으로 수정하고 평균 점수도 다시 계산한다.
del df['평균']
df['영어'][3] = 80  # df.영어[3] = 80 , df['영어']['방자']
df['평균'] = np.round(df.mean(axis=1),1)
df

국어  영어  수학    평균
춘향  80  90  90  86.7
몽룡  90  70  60  73.3
향단  70  60  80  70.0
방자  30  80  70  60.0

In [46]:
# (5) 춘향의 점수를 데이터프레임으로 나타낸다.
df[:'춘향'] # df[:1]

국어  영어  수학    평균
춘향  80  90  90  86.7

In [48]:
df.head(1)

국어  영어  수학    평균
춘향  80  90  90  86.7

In [49]:
df.T[['춘향']]

춘향
국어  80.0
영어  90.0
수학  90.0
평균  86.7

In [50]:
df.head(3).tail(2)  # 중간에 있는 행 출력

국어  영어  수학    평균
몽룡  90  70  60  73.3
향단  70  60  80  70.0

In [51]:
# (6) 향단의 점수를 시리즈로 나타낸다.
df.T['향단']

국어    70.0
영어    60.0
수학    80.0
평균    70.0
Name: 향단, dtype: float64